from __future__ import annotations

from enum import Enum


class FrameConstants(Enum):
    HEAD_FRAME_HEIGHT = 100
    HEAD_FRAME_WIDTH = 1200
    FOOT_FRAME_HEIGHT = 50
    FOOT_FRAME_WIDTH = 1200
    MIDDLE_FRAME_HEIGHT = 600
    MIDDLE_FRAME_WIDTH = 1200
    FULL_FRAME_HEIGHT = 800
    FULL_FRAME_WIDTH = 1200

    FRAME_CORNER_RADIUS = 0
    HEAD_FRAME_FG_COLOR = "#BAC0F6"
    FOOT_FRAME_FG_COLOR = "#BAC0F6"
    MIDDLE_FRAME_FG_COLOR = "#FFFFFF"
    FULL_FRAME_FG_COLOR = "#FFFFFF"

    SUB_FRAME_FG_COLOR = "#E8EAFD"

    TAG_PRIORITY_LIST_FG_COLOR = "#D9D9D9"

    UTILITY_FRAME_CORNER_RADIUS = 8
