from __future__ import annotations

from enum import Enum


class SegmentedButtonConstants(Enum):
    SEGMENTED_BUTTON_CORNER_RADIUS = 8
    SEGMENTED_BUTTON_FG_COLOR = "#FFFFFF"
    SEGMENTED_BUTTON_SELECTED_COLOR = "#FFFFFF"
    SEGMENTED_BUTTON_SELECTED_HOVER_COLOR = "#FFFFFF"
    SEGMENTED_BUTTON_UNSELECTED_COLOR = "#FFFFFF"
    SEGMENTED_BUTTON_UNSELECTED_HOVER_COLOR = "#FFFFFF"
    SEGMENTED_BUTTON_TEXT_COLOR = "#FFFFFF"
    SEGMENTED_BUTTON_TEXT_COLOR_DISABLED = "#FFFFFF"
